export * from './IRepository';
export * from './ICustomerRepository';
export * from './IPartnerRepository';
export * from './IAssetRepository';
export * from './IDeviceRepository';
export * from './IRoleRepository';
export * from './IPolicyRepository';
export * from './IRoleAssignmentRepository';
export * from './IRuleRepository';
