import { Customer } from '../domain/entities/Customer';
import { Partner } from '../domain/entities/Partner';
import { Role } from '../domain/entities/Role';
import { Policy } from '../domain/entities/Policy';
import { RoleAssignment } from '../domain/entities/RoleAssignment';

const TENANT_ID = 'tenant-default';

// Mock Customers with hierarchy
export const mockCustomers: Map<string, Customer> = new Map([
  [
    'cust-001',
    {
      id: 'cust-001',
      tenantId: TENANT_ID,
      parentCustomerId: null,
      path: `/${TENANT_ID}/cust-001`,
      depth: 0,
      name: 'MYIO Holdings',
      displayName: 'MYIO Holdings',
      code: 'MYIO-HLD',
      type: 'HOLDING',
      email: 'contact@myioholdings.com',
      phone: '+55 11 99999-0001',
      settings: {
        timezone: 'America/Sao_Paulo',
        locale: 'pt-BR',
        currency: 'BRL',
        inheritFromParent: false,
      },
      metadata: {},
      status: 'ACTIVE',
      version: 1,
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      createdBy: 'system',
    },
  ],
  [
    'cust-002',
    {
      id: 'cust-002',
      tenantId: TENANT_ID,
      parentCustomerId: 'cust-001',
      path: `/${TENANT_ID}/cust-001/cust-002`,
      depth: 1,
      name: 'Shopping Campinas',
      displayName: 'Shopping Campinas',
      code: 'SHP-CPS',
      type: 'COMPANY',
      email: 'contact@shoppingcampinas.com',
      phone: '+55 19 99999-0002',
      address: {
        street: 'Av. das Amoreiras, 123',
        city: 'Campinas',
        state: 'SP',
        country: 'Brasil',
        postalCode: '13070-000',
        coordinates: { lat: -22.9056, lng: -47.0608 },
      },
      settings: {
        timezone: 'America/Sao_Paulo',
        locale: 'pt-BR',
        currency: 'BRL',
        inheritFromParent: true,
      },
      metadata: { totalArea: 50000, parkingSpots: 2000 },
      status: 'ACTIVE',
      version: 1,
      createdAt: '2026-01-02T00:00:00Z',
      updatedAt: '2026-01-02T00:00:00Z',
      createdBy: 'system',
    },
  ],
  [
    'cust-003',
    {
      id: 'cust-003',
      tenantId: TENANT_ID,
      parentCustomerId: 'cust-001',
      path: `/${TENANT_ID}/cust-001/cust-003`,
      depth: 1,
      name: 'Shopping São Paulo',
      displayName: 'Shopping São Paulo',
      code: 'SHP-SP',
      type: 'COMPANY',
      email: 'contact@shoppingsp.com',
      phone: '+55 11 99999-0003',
      address: {
        street: 'Av. Paulista, 1000',
        city: 'São Paulo',
        state: 'SP',
        country: 'Brasil',
        postalCode: '01310-100',
        coordinates: { lat: -23.5505, lng: -46.6333 },
      },
      settings: {
        timezone: 'America/Sao_Paulo',
        locale: 'pt-BR',
        currency: 'BRL',
        inheritFromParent: true,
      },
      metadata: { totalArea: 80000, parkingSpots: 3500 },
      status: 'ACTIVE',
      version: 1,
      createdAt: '2026-01-02T00:00:00Z',
      updatedAt: '2026-01-02T00:00:00Z',
      createdBy: 'system',
    },
  ],
  [
    'cust-004',
    {
      id: 'cust-004',
      tenantId: TENANT_ID,
      parentCustomerId: 'cust-002',
      path: `/${TENANT_ID}/cust-001/cust-002/cust-004`,
      depth: 2,
      name: 'Loja Âncora Campinas',
      displayName: 'Loja Âncora - Campinas',
      code: 'STR-CPS-001',
      type: 'BRANCH',
      email: 'loja.campinas@ancora.com',
      phone: '+55 19 99999-0004',
      settings: {
        timezone: 'America/Sao_Paulo',
        locale: 'pt-BR',
        currency: 'BRL',
        inheritFromParent: true,
      },
      metadata: { storeArea: 500, floor: 1 },
      status: 'ACTIVE',
      version: 1,
      createdAt: '2026-01-03T00:00:00Z',
      updatedAt: '2026-01-03T00:00:00Z',
      createdBy: 'system',
    },
  ],
  [
    'cust-005',
    {
      id: 'cust-005',
      tenantId: TENANT_ID,
      parentCustomerId: 'cust-003',
      path: `/${TENANT_ID}/cust-001/cust-003/cust-005`,
      depth: 2,
      name: 'Loja Âncora São Paulo',
      displayName: 'Loja Âncora - SP',
      code: 'STR-SP-001',
      type: 'BRANCH',
      email: 'loja.sp@ancora.com',
      phone: '+55 11 99999-0005',
      settings: {
        timezone: 'America/Sao_Paulo',
        locale: 'pt-BR',
        currency: 'BRL',
        inheritFromParent: true,
      },
      metadata: { storeArea: 800, floor: 2 },
      status: 'ACTIVE',
      version: 1,
      createdAt: '2026-01-03T00:00:00Z',
      updatedAt: '2026-01-03T00:00:00Z',
      createdBy: 'system',
    },
  ],
]);

// Mock Partners
export const mockPartners: Map<string, Partner> = new Map([
  [
    'partner-001',
    {
      id: 'partner-001',
      tenantId: TENANT_ID,
      status: 'ACTIVE',
      companyName: 'Energy Solutions Inc',
      companyWebsite: 'https://energysolutions.com',
      companyDescription: 'Energy monitoring and optimization solutions',
      industry: 'Energy',
      country: 'Brasil',
      contactName: 'João Silva',
      contactEmail: 'joao@energysolutions.com',
      contactPhone: '+55 11 99999-1001',
      technicalContactEmail: 'tech@energysolutions.com',
      apiKeys: [
        {
          id: 'key-001',
          keyHash: 'hashed_key_001',
          keyPrefix: 'es_live_',
          name: 'Production Key',
          scopes: ['customers:read', 'assets:read', 'devices:read'],
          createdAt: '2026-01-05T00:00:00Z',
          status: 'ACTIVE',
        },
      ],
      oauthClients: [],
      webhooks: [],
      scopes: ['customers:read', 'assets:read', 'devices:read'],
      rateLimitPerMinute: 100,
      rateLimitPerDay: 10000,
      monthlyQuota: 100000,
      subscribedPackages: [],
      publishedPackages: [],
      approvedAt: '2026-01-05T00:00:00Z',
      approvedBy: 'admin-001',
      version: 1,
      createdAt: '2026-01-04T00:00:00Z',
      updatedAt: '2026-01-05T00:00:00Z',
      createdBy: 'system',
    },
  ],
]);

// Mock Policies
export const mockPolicies: Map<string, Policy> = new Map([
  [
    'policy_admin_full',
    {
      id: 'policy-001',
      tenantId: TENANT_ID,
      key: 'policy_admin_full',
      displayName: 'Full Admin Policy',
      description: 'Full administrative access to all resources',
      allow: ['*.*.*'],
      deny: [],
      riskLevel: 'critical',
      isSystem: true,
      version: 1,
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      createdBy: 'system',
    },
  ],
  [
    'policy_tech_maintenance',
    {
      id: 'policy-002',
      tenantId: TENANT_ID,
      key: 'policy_tech_maintenance',
      displayName: 'Technician Maintenance Policy',
      description: 'Access for maintenance technicians',
      allow: [
        'energy.settings.read',
        'energy.devices.read',
        'energy.devices.list',
        'alarms.rules.read',
        'alarms.rules.list',
        'workorders.orders.create',
        'workorders.orders.read',
        'workorders.orders.update',
        'customers.hierarchy.read',
      ],
      deny: ['identity.*', 'integrations.*'],
      conditions: {
        requiresMFA: false,
      },
      riskLevel: 'medium',
      isSystem: true,
      version: 1,
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      createdBy: 'system',
    },
  ],
  [
    'policy_viewer',
    {
      id: 'policy-003',
      tenantId: TENANT_ID,
      key: 'policy_viewer',
      displayName: 'Viewer Policy',
      description: 'Read-only access',
      allow: ['*.*.read', '*.*.list'],
      deny: ['identity.*'],
      riskLevel: 'low',
      isSystem: true,
      version: 1,
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      createdBy: 'system',
    },
  ],
]);

// Mock Roles
export const mockRoles: Map<string, Role> = new Map([
  [
    'admin',
    {
      id: 'role-001',
      tenantId: TENANT_ID,
      key: 'admin',
      displayName: 'Administrator',
      description: 'Full system administrator',
      policies: ['policy_admin_full'],
      tags: ['admin', 'system'],
      riskLevel: 'critical',
      isSystem: true,
      version: 1,
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      createdBy: 'system',
    },
  ],
  [
    'technician_maintenance',
    {
      id: 'role-002',
      tenantId: TENANT_ID,
      key: 'technician_maintenance',
      displayName: 'Maintenance Technician',
      description: 'Field technician with maintenance capabilities',
      policies: ['policy_tech_maintenance'],
      tags: ['maintenance', 'field'],
      riskLevel: 'medium',
      isSystem: true,
      version: 1,
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      createdBy: 'system',
    },
  ],
  [
    'viewer',
    {
      id: 'role-003',
      tenantId: TENANT_ID,
      key: 'viewer',
      displayName: 'Viewer',
      description: 'Read-only access to data',
      policies: ['policy_viewer'],
      tags: ['viewer', 'readonly'],
      riskLevel: 'low',
      isSystem: true,
      version: 1,
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      createdBy: 'system',
    },
  ],
]);

// Mock Role Assignments
export const mockRoleAssignments: Map<string, RoleAssignment> = new Map([
  [
    'assign-001',
    {
      id: 'assign-001',
      tenantId: TENANT_ID,
      userId: 'user-admin',
      roleKey: 'admin',
      scope: 'tenant:*',
      status: 'active',
      grantedBy: 'system',
      grantedAt: '2026-01-01T00:00:00Z',
      version: 1,
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
  ],
  [
    'assign-002',
    {
      id: 'assign-002',
      tenantId: TENANT_ID,
      userId: 'user-tech-joao',
      roleKey: 'technician_maintenance',
      scope: 'customer:cust-002',
      status: 'active',
      grantedBy: 'user-admin',
      grantedAt: '2026-01-05T00:00:00Z',
      reason: 'Assigned as field technician for Campinas',
      version: 1,
      createdAt: '2026-01-05T00:00:00Z',
      updatedAt: '2026-01-05T00:00:00Z',
    },
  ],
  [
    'assign-003',
    {
      id: 'assign-003',
      tenantId: TENANT_ID,
      userId: 'user-viewer',
      roleKey: 'viewer',
      scope: 'customer:cust-001',
      status: 'active',
      grantedBy: 'user-admin',
      grantedAt: '2026-01-06T00:00:00Z',
      version: 1,
      createdAt: '2026-01-06T00:00:00Z',
      updatedAt: '2026-01-06T00:00:00Z',
    },
  ],
]);

// Helper to get default tenant
export const DEFAULT_TENANT_ID = TENANT_ID;
